[package]
name = "i18n-transform"
version = "0.1.0"
authors = ["Alexander Lüngen <a-luengen@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
structopt = "0.3"